spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "2.0"

accounts:
  message: "Welcome to Aluri accounts related PRODUCTION APIs "
  contactDetails:
    name: "Akhil Aluri - Product Owner"
    email: "{ciper}f7f80ff6676569ec8a9e45ee20f8f42326bc72f1f849dd3156c5d629b1ebaf09"
  onCallSupport:
    - (777) 555-1234
    - (777) 523-1345
